name: Android Build

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Detekt
        run: ./gradlew detekt

  tests:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        run: ./gradlew test

  debug:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Project
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v2
        with:
          name: Debug
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Project
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: Release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}